import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/componenets/Mutualcomponents/Navbar";
import Footer from "@/componenets/Mutualcomponents/Footer";
import { AuthProvider } from "@/context/AuthContext";
import ReduxProvider from "@/context/Reduxprovider";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Keep metadata here (server component)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Client providers go inside */}
        <AuthProvider>
          <ReduxProvider>
            <Navbar />
            {children}
            <Toaster position="top-right" reverseOrder={false} />
            <Footer />
          </ReduxProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
